import type { StorybookConfig } from "@storybook/react-vite";

/**
 * Storybook 10 — React + Vite builder.
 *
 * Layout choices:
 *   - Stories live next to the component (`*.stories.tsx`) plus the
 *     two synthetic groupings under `src/design-tokens/` and
 *     `src/docs/` so the sidebar shows tokens / guides at the top.
 *   - We deliberately don't pull in `@storybook/addon-essentials` —
 *     v9+ split it into individual packages, and most of what
 *     "essentials" used to provide (controls, actions, viewport,
 *     backgrounds, measure, outline, highlight) ships built-in now.
 *   - `addon-docs` powers MDX pages and the autogenerated component
 *     docs (`tags: ["autodocs"]`).
 *   - `addon-a11y` runs axe on every story render — picks up any
 *     regression introduced by a story without us having to remember.
 *   - `addon-themes` wires the theme switcher in the toolbar so the
 *     same story renders against `default`, `high-contrast`, etc.
 *
 * Roadmap (see `STORYBOOK.md`):
 *   - `@storybook/addon-vitest` for in-Storybook test runner.
 *   - Chromatic visual regression in CI.
 *   - MSW addon for fetch-driven feature stories.
 */
const config: StorybookConfig = {
  stories: [
    "../src/docs/**/*.mdx",
    "../src/design-tokens/**/*.@(stories.tsx|mdx)",
    "../src/components/**/*.stories.@(ts|tsx)",
  ],
  addons: [
    "@storybook/addon-docs",
    "@storybook/addon-a11y",
    "@storybook/addon-themes",
  ],
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
  // The static directory matches Vite's — favicons, manifest, and
  // brawler artwork in `/public` resolve at the same paths inside SB.
  staticDirs: ["../public"],
  typescript: {
    // The default is "react-docgen" which is fast but misses
    // `interface Props` and union prop types we use everywhere.
    // `react-docgen-typescript` is slower but produces richer docs.
    reactDocgen: "react-docgen-typescript",
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      // Skip prop introspection for types defined outside our source
      // tree — keeps the Controls panel readable (no `React.HTMLProps`
      // explosion) and the build fast.
      propFilter: (prop) =>
        !prop.parent || !/node_modules/.test(prop.parent.fileName),
    },
  },

  /**
   * Storybook's Vite builder picks up the project's `vite.config.ts`
   * automatically. Several of our plugins don't make sense (and
   * actively fail) inside the Storybook iframe build:
   *
   *   - `vite-plugin-pwa` registers a family of sub-plugins with
   *     names like `vite-plugin-pwa`, `vite-plugin-pwa:build`,
   *     `vite-plugin-pwa:dev-sw`. They generate a service worker
   *     from the bundle output, which conflicts with Storybook's
   *     chunked output (workbox throws "Unexpected early exit").
   *   - `vite-plugin-compression` writes `.br` / `.gz` siblings
   *     during prod builds — useless for a Storybook static site.
   *   - `rollup-plugin-visualizer` writes `dist/stats.html` into
   *     the wrong directory.
   *
   * We strip all three by prefix match before the iframe build runs.
   * Plugin entries can be nested arrays (Vite flattens them) so we
   * walk recursively. Everything else (React plugin, Tailwind) keeps
   * working so stories look exactly like production.
   */
  viteFinal: async (viteConfig) => {
    const dropPrefixes = ["vite-plugin-pwa", "vite-plugin-compression", "visualizer"];

    type AnyPlugin = { name?: string } | null | false | undefined | AnyPlugin[];
    const shouldDrop = (plugin: AnyPlugin): boolean => {
      if (!plugin || typeof plugin !== "object") return false;
      if (Array.isArray(plugin)) return false;
      const name = plugin.name;
      if (!name) return false;
      return dropPrefixes.some((prefix) => name.startsWith(prefix));
    };

    const filterRecursive = (plugins: AnyPlugin[]): AnyPlugin[] =>
      plugins
        .filter((p) => !shouldDrop(p))
        .map((p) => (Array.isArray(p) ? filterRecursive(p) : p));

    if (Array.isArray(viteConfig.plugins)) {
      viteConfig.plugins = filterRecursive(viteConfig.plugins as AnyPlugin[]) as typeof viteConfig.plugins;
    }
    return viteConfig;
  },
};

export default config;
